fix spacing on mobile only
ihateerrors/omfs-nepa pull request #20
Opened 2024-02-16 00:09 UTC by Gengur123

2024-02-17 00:02 UTC, benbogard requested changes
when I pull this down, I am not seeing any changes related to adding these classes. However, I did see spacing added in this pr : https://github.com/ihateerrors/omfs-nepa/pull/19 perhaps there is some confusion here?

2024-02-17 01:16 UTC, Gengur123 commented
I believe I added spacing between each of the hamburger menu nav items, to be honest it does look still pretty similar to the one on live. I can add more space between it to make it more noticeable.

2024-02-21 18:43 UTC, benbogard approved these changes

2024-02-21 18:54 UTC, merged

2024-02-21 19:35 UTC, benbogard reviewed
just move it along